### ISSUE TITLE
Build an End-to-End Dapp on Aptos

### ISSUE THREAD

**Issue by nphacks** [aptos-labs/developer-docs#605]
### Url

https://aptos.dev/en/build/guides/build-e2e-dapp

### Describe the content issue

Completed all 6 steps.
I get two main errors: 
1. I get the 404 on ToDoList "AptosApiError: Request to [Fullnode]: GET https://api.devnet.aptoslabs.com/v1/accounts/<petra_wallet_address>)/resource/<module_address>::todolist::TodoList failed with: {"message":"Resource not found by Address(<wallet_address>), Struct tag(<module_address>::todolist::TodoList) and Ledger version(68845922)","error_code":"resource_not_found","vm_error_code":null}
    at y (core.ts:100:1)
    at async x (account.ts:174:1)
    at async fetchList (App.tsx:39:1)"

2. When trying to add new list, I have tried to connect all wallets but always end up with the following error on signature request popup up. I don't know why the error says mainnet when I am tryin to be on devnet.  
"Simulation error
Request to [Fullnode]: GET https://fullnode.mainnet.aptoslabs.com/v1/accounts/<address> (trace_id:f25221a670099c0ce351765810904cad) failed with: {"message":"Account not found by Address(<wallet_address><address>) and Ledger version(1706012087)","error_code":"account_not_found","vm_error_code":null}"

My smart contract is published
Transaction submitted: https://explorer.aptoslabs.com/txn/<hash>?network=devnet
{
  "Result": {
    "transaction_hash": "<hash>",
    "gas_used": 71,
    "gas_unit_price": 100,
    "sender": "<sender_address>",
    "sequence_number": 1,
    "success": true,
    "timestamp_us": 1726590490780856,
    "version": 68777722,
    "vm_status": "Executed successfully"
  }
}

I have done entire process thrice, but always the same results. Has something changed or missing? I am very novice to solve this kind of error yet.

### Section

create-aptos-dapp

**Comment by gregnazario** [comment]
cc @0xmaayan perhaps, we replace this tutorial entirely with create-aptos-dapp?
